// Minifies src/c.js and writes it as dist/c.js and as a string in src/generated.ts.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { transformSync } from 'esbuild'

const root = new URL('..', import.meta.url)
const source = readFileSync(new URL('src/c.js', root), 'utf8')
const { code } = transformSync(source, { minify: true, target: 'es2017' })
const minified = code.trim()
// The placeholder is a property read so the minifier cannot fold it away as a constant.
const PLACEHOLDER = /\b\w+\.__COPPER_ENDPOINT__/
if (!PLACEHOLDER.test(minified)) {
  throw new Error('The endpoint placeholder did not survive minification.')
}
mkdirSync(new URL('dist/', root), { recursive: true })
writeFileSync(new URL('dist/c.js', root), minified.replace(PLACEHOLDER, '""'))
writeFileSync(
  new URL('src/generated.ts', root),
  `// Generated by scripts/build.mjs from src/c.js. Do not edit.\nexport const TRACKER_TEMPLATE = ${JSON.stringify(minified)}\n`,
)
